site_name: COMP423 Course Notes
theme:
  name: material
markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition

nav:
  - Home: index.md
  - Go Setup: tutorials/go-setup.md
